# Generated by Django 5.1 on 2024-08-29 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0002_alter_urls_long_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Urls',
            new_name='Url',
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('browser_client', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_visits', to='shorten.url')),
            ],
        ),
        migrations.DeleteModel(
            name='Visits',
        ),
    ]
