# Generated by Django 5.1 on 2024-08-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0003_rename_urls_url_visit_delete_visits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='url',
            name='status',
            field=models.CharField(choices=[('a', 'ACTIVE'), ('i', 'INACTIVE'), ('s', 'SUSPENDED')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='url',
            name='url_code',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='visit',
            name='browser_client',
            field=models.CharField(max_length=255),
        ),
    ]
