services:
  web:
    build:
      context: ./app
    command: ./wait-for-it.sh mysql:3306 -t 60 -- ./docker-entrypoint.sh
    ports:
      - 8000:8000
    depends_on:
      - redis
      - mysql
    restart: on-failure
    volumes:
      - ./app:/app
  mysql:
    image: mysql:8.0
    ports:
      - 3307:3306
    restart: always
    environment:
      - MYSQL_DATABASE=shortener
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
    volumes:
      - mysqldata:/var/lib/mysql
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redisdata:/data
volumes:
  mysqldata:
  redisdata:
